# Dependencies
markdown:            redcarpet
highlighter:         rouge

# Setup
title:               Chocolate Fudge
tagline:             "The mind's meanderings"
description:         'Random thoughts, wierd insights and wonkish rants.'
url:                 http://auag92.github.io
baseurl:             /learning-atomistics
paginate:            10

# About/contact
author:
  name:              Apaar Shanker
  url:               https://twitter.com/apaarshanker
  email:             apaar92@gmail.com

# Custom vars
version:             1.0.0

gems: ["emoji_for_jekyll"]

timezone: Asia/Kolkata
future: False
