# Dependencies
markdown:            kramdown
highlighter:         rouge

# Setup
title:               Project Blog
tagline:             "All models are wrong, but some are useful"
description:         'A repository for discussion, resources and other content related our study'
url:                 http://auag92.github.io
baseurl:             /learning-atomistics
paginate:            5

# About/contact
author:
  name:              Apaar Shanker
  url:               https://www.linkedin.com/in/apaar-shanker-47098252/
  email:             apaar92@gmail.com

# Custom vars
version:             0.0.1

gems: ["emoji_for_jekyll"]

timezone: America/New_York
future: False
